"""add foreign key to onboarding

Revision ID: 9979cb652468
Revises: dd49e6a2f470
Create Date: 2025-09-16 08:21:05.945194

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9979cb652468'
down_revision = 'dd49e6a2f470'
branch_labels = None
depends_on = None


def upgrade():
    # onboardings table
    with op.batch_alter_table('onboardings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('employee_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
            op.f('fk_onboardings_employee_id_employees'),
            'employees',
            ['employee_id'],
            ['id']
        )

    # reviews table
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.create_foreign_key(
            op.f('fk_reviews_employee_id_employees'),
            'employees',
            ['employee_id'],
            ['id']
        )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_reviews_employee_id_employees'), 'reviews', type_='foreignkey')
    op.drop_constraint(op.f('fk_onboardings_employee_id_employees'), 'onboardings', type_='foreignkey')
    op.drop_column('onboardings', 'employee_id')
    # ### end Alembic commands ###
